server:
  port: 8081
  session:
    timeout: 1800
  #address: acount.yayao8.com
  tomcat:
    max-threads: 1000
    min-spare-threads: 200
    accept-count: 1000
    max-connections: 1000
 # connection-timeout: 60 
spring:
   datasource:
     name: master
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://39.108.60.100:3306/convert_mall_db
     username: root
     password: liliu
   redis:
     host: 39.108.60.100
     password: liliu
     port: 6379 
     database: 1
     timeout: 3000
     pool: 
       min-idle: 100
       max-idle: 300
       max-active: 800 
myPugin: 
  session: 
    myDomainName: newzhuan.cn
  projectName: ConvertMall
  location: /home/config/thirdParty.properties
  requestAuth: requestAuthProd
  rabbitmq:
    MERORDER_DIRECT_EXCHANGE: merorder.convertmall.exchange.direct
    MERORDER_DIRECT_ROUTINGKEY: merorder.convertmall.routingkey.direct
    MERORDER_DIRECT_QUEUE: merorder.convertmall.queue.direct
    FLOWWATER_DIRECT_EXCHANGE: flowwater.convertmall.exchange.direct
    FLOWWATER_DIRECT_ROUTINGKEY: flowwater.convertmall.routingkey.direct
    FLOWWATER_DIRECT_QUEUE: flowwater.convertmall.queue.direct